### PR TITLE
Add ili2db's exportMetaConfig operation

### PR DESCRIPTION
**Pull request by gacarrillor**
Also, replace parsing the ili2db settings from the ili2db's metadata tables by parsing the metaConfig ini file produced by the ili2db's `exportMetaConfig` command.

### CODE REVIEW

**Comment by gacarrillor** [comment]
@signedav, should we get rid of `parse_parameters_from_db` https://github.com/opengisch/QgisModelBakerLibrary/blob/e21e7095f3e9d95b355982c7c330239bf17e8d49/modelbaker/ilitoppingmaker/ili2dbsettings.py#L36?

**Comment by signedav** [comment]
> @signedav, should we get rid of parse_parameters_from_db
yes

**Comment by gacarrillor** [comment]
> > @signedav, should we get rid of parse_parameters_from_db
> 
> yes

Done.

**Review by signedav — APPROVED** [review]
Looks good. Thanks.

**Pull request merged**
