### PR TITLE
Add support for translated models

### PR DESCRIPTION
**Pull request by gacarrillor**
+ [x] Pass `--createNlsTab` parameter to schema info operation.
 + [x] Ignore `t_ili2db_nls` table.

 + [x] GPKG
   + [x] Tables
   + [x] Columns
   + [x] Relationships
   + [x] Tabs
   + [ ] Domain values (see #115)
 + [x] PG and MSSQL
   + [x] Tables
   + [x] Columns
   + [x] Relationships
   + [x] Tabs
   + [ ] Domain values (see #115)

Screenshot from 2024-10-28 21-48-15

Requires ili2db v5.2.0
References https://github.com/opengisch/QgisModelBaker/pull/971

### CODE REVIEW

**Comment by gacarrillor** [comment]
Tests are failing because ili2db 5.2.0 is still not found as a release.

**Review by signedav — APPROVED** [review]

**Comment by signedav** [comment]
https://github.com/claeis/ili2db/commit/e4379495895771db8113dd56a4fe23f3ceae5419 See this

As well the domain issue is solved in the next release of ili2db

**Comment by signedav** [comment]
Can we merge that as soon we have 5.2 @gacarrillor ?

**Comment by gacarrillor** [comment]
> Can we merge that as soon we have 5.2 @gacarrillor ?

Would be great indeed. I'll work on unit tests in the meantime.

**Comment by gacarrillor** [comment]
Tests will fail in GitHub until ili2db 5.2.0 is published.
They're passing on a local environment pointing to a ili2db 5.2.0 snapshot.

**Comment by signedav** [comment]
@gacarrillor Several tests are failing with 5.2.0 I guess you only run your new test locally and not all the tests. Right? Otherwise there is something else not okay...

**Pull request merged**
