### PR TITLE
Validator --skipGeometryCheck and --validConfig options

### PR DESCRIPTION
**Pull request by domi4484**

### CODE REVIEW

**Comment by signedav** [comment]
Can you add tests for that? Maybe with the project from the Clickup Project.

**Comment by domi4484** [comment]
@signedav the new test is failing with an error. Is it maybe because I try to use a gpkg with data already in it? I have seen in all other test you import data from an XTF file. Do you have an idea what I do wrong here?

```
ERROR    root:test_validate.py:440 no baskets with given model names in table T_ILI2DB_BASKET
```

**Comment by signedav** [comment]
Not sure but apparently you do an `schemaimport` but no import of the data and then a validation on the gpkg. Why you do a schemaimport? This should not be needed. And you need to pass the Baseset (or the model) at least one of those parameters. 

But maybe it's more proper to generate the gpkg. Means you do your schema import and then an import of the data to validate (like in the other tests). To generate the xtf you make an export on the existing GPKG. Should i do it for you, since I set it up?

**Comment by domi4484** [comment]
@signedav i though as i already have a fix finish gpkg I can use it... I'll change it like the other tests using an xtf.
Thanks for the offer but I should slowly be able to export an xtf 😁

**Comment by signedav** [comment]
You just have to disable the validationon the export (and import (schema and data)...

**Comment by domi4484** [comment]
I have disabled it but still receiving an error on import about sqlite constraint violation. Can I disable them on database creation?
```
        # Import valid data to Baseset
        dataImporter.configuration.dataset = "Baseset"
        dataImporter.configuration.xtffile = testdata_path("xtf/test_validate_skip.xtf")
        assert dataImporter.run() == iliimporter.Importer.ERROR
        dataImporter.configuration.disable_validation = True
>       assert dataImporter.run() == iliimporter.Importer.SUCCESS
E       AssertionError: assert 1000 == 0
E        +  where 1000 = <bound method IliExecutable.run of <modelbaker.iliwrapper.iliimporter.Importer object at 0x7fe2d3f080d0>>()
E        +    where <bound method IliExecutable.run of <modelbaker.iliwrapper.iliimporter.Importer object at 0x7fe2d3f080d0>> = <modelbaker.iliwrapper.iliimporter.Importer object at 0x7fe2d3f080d0>.run
E        +  and   0 = <class 'modelbaker.iliwrapper.iliimporter.Importer'>.SUCCESS
E        +    where <class 'modelbaker.iliwrapper.iliimporter.Importer'> = iliimporter.Importer
```

```
ERROR    root:test_validate.py:461 Info: process data file...
Info: data </usr/src/tests/testdata/xtf/test_validate_skip.xtf>

ERROR    root:test_validate.py:461 Info: Basket Brutalism.Buildings(oid 2c52fabf-e981-41c0-a69d-c416f26e8ad1)...

ERROR    root:test_validate.py:461 Error: Object 2bc9bcaf-4dcd-46dc-ae0f-4755a785faac at (line 5,col 74)
Error:   [SQLITE_CONSTRAINT]  Abort due to constraint violation (NOT NULL constraint failed: resident.aobject)

ERROR    root:test_validate.py:461 Error: Object f38792a5-8416-4144-b086-d47272ba88cb at (line 7,col 72)
Error:   [SQLITE_CONSTRAINT]  Abort due to constraint violation (NOT NULL constraint failed: aobject.aname)

ERROR    root:test_validate.py:461 ...import failed
```

**Comment by signedav** [comment]
Coolio..can you remove the unused gpkg? Then we merge.

**Review by signedav — APPROVED** [review]

**Pull request merged**
